#!/bin/bash
# Author   :    AlicFeng & GuiGos
# Email    :    a@samego.com / guillaume@guigos.com
# Github   :    https://github.com/Gui-Gos/sshAutoLogin

# set color variables for 'printf' or 'echo'; example 'printf "${Green}"$VARIABLE" or text${ResetColor}\n"'
Red="\e[0;31m"
Green="\e[0;32m"
Yellow="\e[0;33m"
Blue="\e[0;34m"
ResetColor="\e[0m"

# loads the list of servers
server_list=()
# set the working folder
Config_Dir=~/.ssha
# determines if the configuration folder exists
if [ -d $Config_Dir ];then
	# Path of each '.ini or .conf' configuration file
	for config_file in "$Config_Dir"/*;do 
		if [ "${config_file##*.}"x = "ini"x ]||[ "${config_file##*.}"x = "conf"x ];then
    			while read -r line_configure;do
                    eval "$line_configure"
				done < "$config_file"
                server_list[${#server_list[*]}]="${Index} ${Name} ${Host} ${Port} ${User} ${PasswordOrKey}"
		else
			printf "${Red}Your server configuration files are not in the correct format (.ini/.conf)${ResetColor}\n" && exit 1
		fi
	done
else
# if the configuration folder does not exists, create folder and config file
printf  "${Red}Your working folder '$Config_Dir' does not exist${ResetColor}\n"
printf "${Green}Go to create directory '$Config_Dir' and set permissions${ResetColor}\n"
mkdir ~/.ssha
chmod -R 700 $Config_Dir
chown -R "$(whoami)" $Config_Dir
printf "${Green}Go to create your first configuration '0_localhost.ini' file${ResetColor}\n"
printf "Index=0\nName=localhost\nHost=127.0.0.1\nPort=22\nUser=root\nPasswordOrKey=password\n" > ~/.ssha/0_localhost.ini
chmod 700 ~/.ssha/0_localhost.ini
chown "$(whoami)" ~/.ssha/0_localhost.ini
ssha -h
fi

# server length
server_list_length=${#server_list[*]}

# deleted servers
DeletedFolder=~/.ssha/.deleted
if [ -d $DeletedFolder ];then
    # re order the servers list
    serversNewIndex=0
        for ((i=0;i<"$server_list_length";i++));do
        servers=(${server_list[$i]})
        rm ~/.ssha/$servers*
        printf "Index=$serversNewIndex\nName=${servers[1]}\nHost=${servers[2]}\nPort=${servers[3]}\nUser=${servers[4]}\nPasswordOrKey=${servers[5]}\n" > ~/.ssha/"$serversNewIndex"_${servers[1]}.ini
        chmod 700 ~/.ssha/"$serversNewIndex"_${servers[1]}.ini
        serversNewIndex=$((serversNewIndex + 1))
        done
    rmdir $DeletedFolder
fi

##############################
# FUNCTION # list servers
##############################
function list() {
    printf "\n${Blue}Index\tDescription\tHost\tPort\tUsername\tPassword|SecretKeyFile${ResetColor}\n"
    for ((i=0;i<"$server_list_length";i++));do
        servers=(${server_list[$i]})
        printf "${servers[0]}\t${servers[1]}\t${servers[2]}\t${servers[3]}\t${servers[4]}\t${servers[5]}" | toilet -f term -F border -t
    done
    exit 0
}

##############################
# FUNCTION # usage of bin
##############################
function usage() {
printf "\n${Red}USAGE:${ResetColor}\n"
printf "${Blue}ssha${ResetColor} [${Blue}-h${ResetColor}] [${Green}-l${ResetColor}] [${Green}-c${ResetColor}] [${Green}-d${ResetColor}] [${Green}-s <server number>${ResetColor}]\n"
    exit 0
}

##############################
# FUNCTION # login to server
##############################
function login() {
    server=(${server_list[$1]})
    v5NZ8jBr2HoQYD=${server[5]}
    zodVApcRdLi4Kz=$(printf '%s' "$v5NZ8jBr2HoQYD" | base64 --decode)
    pem="$zodVApcRdLi4Kz"
    printf "${Blue}$USER${ResetColor} ${Green}logging${ResetColor} into the${Yellow}【${server[1]}】${ResetColor}server" | toilet -f term -F border
	command="
        expect {
                \"*assword\" {set timeout 6000; send \"$pem\n\"; exp_continue ; sleep 3; }
                \"*passphrase\" {set timeout 6000; send \"$pem\r\n\"; exp_continue ; sleep 3; }
                \"yes/no\" {send \"yes\n\"; exp_continue;}
                \"Last*\" {  send_user \"\nsuccessfully logined 【${server[1]}】\n\";}
        }
       interact
    ";
   if [ -f "$pem" ]
   then
	expect -c "
		spawn ssh -p ${server[2]} -i $pem ${server[3]}@${server[2]}
		${command}
	"
   else
	expect -c "
		spawn ssh -p ${server[3]} ${server[4]}@${server[2]}
		${command}
	"
   fi
    printf "${Blue}$USER${ResetColor} ${Red}logged out${ResetColor} the${Yellow}【${server[1]}】${ResetColor}server" | toilet -f term -F border
}

##############################
# FUNCTION # create server
##############################
function create() {
printf "\n${Blue}Creating a new server:${ResetColor}\n"
#number=$(ls ~/.ssha | wc -l | tr -d '[:blank:]')
printf "${Yellow}Please type the '${Blue}Description${Yellow}' of this server:${ResetColor}\n"
read -r name
printf "${Yellow}Please type the '${Blue}Hostname|IP${Yellow}' of this server:${ResetColor}\n"
read -r host
printf "${Yellow}Please type the '${Blue}Port${Yellow}' of this server:${ResetColor}\n"
read -r port
printf "${Yellow}Please type the '${Blue}Username${Yellow}' of this server:${ResetColor}\n"
read -r user
printf "${Yellow}Please type the '${Blue}Password|SecretKeyFile${Yellow}' of this server:${ResetColor}\n"
read -r pass && v5NZ8jBr2HoQYD=$(printf '%s' "$pass" | base64) && unset pass

# Print all data for verification #
printf "\n${Blue}Please check the following informations:${ResetColor}\n"
printf "${Yellow}Name of server:${Green} $name ${ResetColor}\n"
printf "${Yellow}Hostname or IP:${Green} $host ${ResetColor}\n"
printf "${Yellow}Port:${Green} $port ${ResetColor}\n"
printf "${Yellow}Username:${Green} $user ${ResetColor}\n"
printf "${Yellow}Password/Key (hidden):${Green} $pass ${ResetColor}\n"

# Informations is correct ?! #
printf "\n${Blue}Informations is correct ?! (Y/N)${ResetColor}\n"
read -r info
if [[ "$info" =~ ^[yYoO] ]]; then
	printf "\n${Green}'OK' ${Blue}Added server $name to the list${ResetColor}\n"
	printf "Index=$server_list_length\nName=$name\nHost=$host\nPort=$port\nUser=$user\nPasswordOrKey=$v5NZ8jBr2HoQYD\n" | tee -a ~/.ssha/"$server_list_length"_"$name".conf
    chmod 700 ~/.ssha/"$server_list_length"_"$name".conf
    printf "\n${Blue}Congratulations the server${Green} '$name' ${Blue}is well registered. ${ResetColor}Here is the current list of your servers:\n" | toilet -f term -F border
    ssha -l
    exit 0
elif [[ "$info" =~ ^[nN] ]]; then
	printf "\n${Green}'OK' ${Blue}Go to restart creation of server${ResetColor}\n"
	ssha -c
		else
            printf "\n${Red}'INPUT ERROR' ${Blue}Exit${ResetColor}\n"
	        exit 1
fi
}

##############################
# FUNCTION # delete server
##############################
function delete() {
# see list of servers
ssha -l
#number=$(ls ~/.ssha | wc -l | tr -d '[:blank:]')
printf "\n${Blue}Which server do you want to delete ? ${Yellow}(Enter the number)${ResetColor}\n"
read -r srvnb
if [[ ! $srvnb -lt $server_list_length ]]; then
printf "\n${Red}'INPUT ERROR' ${Blue}Exit${ResetColor}\n"
exit 1
else
printf "\n${Blue}You have selected the server ${Green}$srvnb${Blue}. Do you really want to delete this server ? (Y/N)${ResetColor}\n"
    read -r info
    if [[ "$info" =~ ^[yYoO] ]]; then
    printf "\n${Green}'OK' ${Blue}Delete server number ${Green}$srvnb${ResetColor}\n"
    rm ~/.ssha/$srvnb*
    mkdir $DeletedFolder
    # call binary to check deleted folder and re order servers list & exit 0
    ssha
    elif [[ "$info" =~ ^[nN] ]]; then
        printf "\n${Green}'OK' ${Blue}Go restart delete server${ResetColor}\n"
        ssha -d
            else
                printf "\n${Red}'INPUT ERROR' ${Blue}Exit${ResetColor}\n"
                exit 1
    fi
fi
}

##############################
# FUNCTION # test
##############################
function test() {
echo "#############server_list[@]###############"
echo "${server_list[@]}"
echo "#############server_list[*]################"
echo "${#server_list[*]}"
echo "#############$server_list_length###############"
echo "$server_list_length"
}

##############################
# SCRIPT # get ARGS
##############################
while getopts hlcdts: ARGS
do
case $ARGS in
    h)
        usage
        ;;
    l)
        list
        ;;
    c)
        create
        ;;
    d)
        delete
        ;;
    t)
        test
        ;;
    s)
        login "$OPTARG"
        ;;
    *)  
        usage
        ;;
esac
done
